config/routes.rb
CampuspartyGallery::Application.routes.draw do
  devise_for :users

  resources :images

  resources :galleries do
    resources :images
  end

  root :to => "galleries#index"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :gallery

    mount_uploader :file, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  respond_to :html
  skip_before_filter :authenticate_user!, :only => [:index, :show ]
  
  # GET /galleries
  # GET /galleries.xml
  def index
    respond_with(@galleries = Gallery.all.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 5))
  end

  # GET /galleries/1
  # GET /galleries/1.xml
  def show
    respond_with(@gallery = Gallery.find(params[:id]))
  end

  # GET /galleries/new
  # GET /galleries/new.xml
  def new
    respond_with(@gallery = Gallery.new)
  end

  # GET /galleries/1/edit
  def edit
    respond_with(@gallery = Gallery.find(params[:id]))
  end

  # POST /galleries
  # POST /galleries.xml
  def create
    respond_with(@gallery = Gallery.create(params[:gallery]), :status => :created)
  end

  # PUT /galleries/1
  # PUT /galleries/1.xml
  def update
    @gallery = Gallery.find(params[:id])
    @gallery.update_attributes(params[:gallery])
    respond_with(@gallery, :status => :updated)
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.xml
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    respond_with(@gallery, :status => :deleted, :location => galleries_path)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  respond_to :html
  skip_before_filter :authenticate_user!, :only => [:index, :show ]
  
  # GET /images
  # GET /images.xml
  def index
    respond_with(@images = Image.where(:gallery_id => params[:gallery_id]).all.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 5))
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    respond_with(@image = Image.find(params[:id]))
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    respond_with(@image = Image.new)
  end

  # GET /images/1/edit
  def edit
    respond_with(@image = Image.find(params[:id]))
  end

  # POST /images
  # POST /images.xml
  def create
    respond_with(@image = Image.create(params[:image]), :status => :created)
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])
    @image.update_attributes(params[:image])
    respond_with(@image, :status => :updated)
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    respond_with(@image, :status => :deleted, :location => images_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/galleries/_form.html.haml
= simple_form_for(@gallery) do |f|
  = render :partial => "shared/errors", :object => @gallery.errors
  .field
    = f.input :name
  .field
    = f.input :description
  .actions
    = f.submit

app/views/galleries/_gallery.html.haml
%tr
  %td= gallery.name
  %td= link_to 'images', gallery_images_path(gallery)
  %td= link_to 'Show', gallery
  %td= link_to 'Edit', edit_gallery_path(gallery) unless current_user.nil?
  %td= link_to 'Destroy', gallery, :confirm => 'Are you sure?', :method => :delete unless current_user.nil?

app/views/galleries/edit.html.haml
%h1 Editing gallery
= render 'form'
= link_to 'Show', @gallery
|
\#{link_to 'Back', galleries_path}

app/views/galleries/index.html.haml
%div{:class => 'span-24 last'}
  %h1 Listing galleries
  %table
    %tr
      %th='Gallery name'
      %th='Images'
      %th='Show'
      %th='Delete' unless current_user.nil?
    = render :partial => @galleries
  %br/
  = will_paginate @galleries
  %br/
  = link_to 'New Gallery', new_gallery_path unless current_user.nil?

app/views/galleries/new.html.haml
%div{:class => 'span-22 prepend-2 last'}
  %h1 New gallery
  = render 'form'
  = link_to 'Back', galleries_path

app/views/galleries/show.html.haml
%p#notice= notice
= show_for @gallery do |a|
  = a.attribute :name
  = a.attribute :description
- unless current_user.nil?
  = link_to 'Edit', edit_gallery_path(@gallery)
  \|
\#{link_to 'Back', galleries_path}

app/views/images/_form.html.haml
= simple_form_for @image, :html => {:multipart => true} do |f|
  = render :partial => 'shared/errors', :object => @image.errors

  .field
    = f.input :file, :as => :file
  .field
    = f.hidden_field :gallery_id, :value => params[:gallery_id]
  .actions
    = f.submit 'Save'

app/views/images/_image.html.haml
%tr
  %td= image_tag image.file.url(:thumb)
  %td= image.gallery.name
  %td= link_to 'Show', image
  %td= link_to 'Edit', edit_image_path(image) unless current_user.nil?
  %td= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete unless current_user.nil?

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', gallery_images_path(@image.gallery)

app/views/images/index.html.haml
%h1 Listing images

%table
  %tr
    %th File
    %th Gallery
    %th
    %th
    %th

  = render :partial => @images

%br
  = will_paginate @images
%br

- unless current_user.nil?
  = link_to 'New image', new_gallery_image_path
  \|

= link_to 'Back', galleries_path unless current_user.nil?

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p
  %b File:
  = image_tag @image.file.url
%p
  %b Gallery:
  = @image.gallery.name
- unless current_user.nil?
  = link_to 'Edit', edit_image_path(@image)
  \|
= link_to 'Back', gallery_images_path(@image.gallery)

app/views/layouts/_footer.html.haml
%div{:id => 'footer', :class => "span-24 last"}
  %p="Copyright &copy; 2010. MonsterLabs, All Rights Reserved.".html_safe
  %br
  %p='For educational purposes only.'

app/views/layouts/_header.html.haml
%div{:id => 'header'}
  %div{:id => 'title'}
    = image_tag('logo.png', :size => '80x95', :style => 'display: inline-block;')
    = link_to "MonsterLabs", "http://monsterlabs.com.mx", :target => '_new'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CampuspartyGallery
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'gallery'

    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = render :partial => 'layouts/header'
    = render :partial => "shared/session"
    %div{:class =>'container'}

      %p.notice= notice
      %p.alert= alert
      = yield

    = render :partial => 'layouts/footer'

app/views/shared/_errors.html.haml
- if errors.any?
  #error_explanation
    %h2
      = pluralize(errors.count, "error")
      prohibited this gallery from being saved:
    %ul
      - errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_session.html.haml
%div{:id => 'session'}
  - unless current_user.nil?
    = link_to 'Exit', destroy_user_session_path
  - else
    = link_to 'Enter', new_user_session_path